[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXTAUTH_SECRET = "aB3dE5fG7hI9jK1lM2nO3pQ4rS5tU6vW7xY8zA9bC0dE1fG2hI3jK4lM5nO6pQ7rS8tU9vW0xY1zA2bC3dE4fG5hI6="
  NEXTAUTH_URL = "https://app.the47.xyz"
  NEXT_PUBLIC_APP_URL = "https://app.the47.xyz"

[[plugins]]
  package = "@netlify/plugin-nextjs"
